pipeline {
    agent any

    parameters {
        string(name: 'envName', defaultValue: 'env', description: 'Enter the environment name')
        string(name: 'mysqlPassword', defaultValue: 'pwd123', description: 'Enter the MySQL password')
        string(name: 'mysqlPort', defaultValue: '3306', description: 'Enter the MySQL port')
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t mysql-image:latest images/sql-latest/Dockerfile .'
            }
        }

        stage('build Container') {
            steps {
                sh 'docker run --name ${envName} -e MYSQL_ROOT_PASSWORD=${mysqlPassword} -p ${mysqlPort}:3306 -d mysql-image:latest'
            }
        }

        stage('Prepare Environment') {
            steps {
                sh 'docker exec -it ${envName} mysql -u root -p${mysqlPassword} -e "CREATE USER \'aubay\'@\'localhost\'
